# 0. 초기 설정 및 데이터로드

In [20]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [21]:
# import usage libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import os

# 시각화 OS별 한글폰트 설정
if os.name == 'nt':
    plt.rcParams['font.family'] = 'Malgun Gothic'  # Windows 폰트 설정
elif os.name == 'posix':
    plt.rcParams['font.family'] = 'AppleGothic'  # Mac 폰트 설정

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)


# 1. 데이터 불러오기
bnb_raw = pd.read_csv('/content/drive/MyDrive/심화프로젝트/data/2025_Airbnb_NYC_listings.csv') #코랩 공유용 경로(My Drive에 공유폴더 바로가기 추가 필요)
# bnb_raw = pd.read_csv('2025_Airbnb_NYC_listings.csv') # 로컬용 접근경로(동일폴더)


# 2. 복사본 생성(전처리는 복사본으로 진행)
bnb = bnb_raw.copy()

# 1. 원본 데이터 정보

## 1.1 : 원본 데이터 head 탐색

In [22]:
bnb.head()

,Unnamed: 0,id,source,name,description,neighborhood_overview,host_id,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,availability_eoy,number_of_reviews_ly,estimated_occupancy_l365d,estimated_revenue_l365d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,0,36121,city scrape,Lg Rm in Historic Prospect Heights,Cozy space share in the heart of a great neigh...,Full of tree-lined streets and beautiful brown...,62165,Michael,2009-12-11,"New York, NY",I’m an urban planner working for an internatio...,NaN,NaN,NaN,f,Prospect Heights,1.0,3.0,"['email', 'phone', 'work_email']",t,t,Neighborhood highlights,Prospect Heights,Brooklyn,40.673760,-73.966110,Private room in rental unit,Private room,1,1.0,1 shared bath,1.0,1.0,"[""Refrigerator"", ""Dishes and silverware"", ""Wif...",$200.00,90,365,90.0,90.0,365.0,365.0,90.0,365.0,NaN,t,27,57,87,362,2025-03-03,9,0,0,301,0,0,0.0,2010-12-11,2013-05-10,4.88,5.00,4.80,5.00,5.00,5.00,5.00,NaN,f,1,0,1,0,0.05
1,1,36647,city scrape,"1 Bedroom & your own Bathroom, Elevator Apartment",Private bedroom with your own bathroom in a 2 ...,"Manhattan, SE corner of 2nd Ave/ E. 110th street",157798,Irene,2010-07-04,"New York, NY",NaN,NaN,NaN,100%,f,East Harlem,1.0,1.0,"['email', 'phone']",t,t,Neighborhood highlights,East Harlem,Manhattan,40.792454,-73.940742,Private room in condo,Private room,2,1.0,1 private bath,1.0,1.0,"[""Oven"", ""Blender"", ""Luggage dropoff allowed"",...",$82.00,30,999,30.0,30.0,999.0,999.0,30.0,999.0,NaN,t,0,0,0,204,2025-03-03,102,0,0,143,0,0,0.0,2010-10-04,2023-12-09,4.77,4.82,4.76,4.88,4.90,4.38,4.71,NaN,f,1,0,1,0,0.58
2,2,38663,city scrape,Luxury Brownstone in Boerum Hill,"Beautiful, large home in great hipster neighbo...","diverse, lively, hip, cool: loaded with restau...",165789,Sarah,2010-07-13,"New York, NY",I am a lawyer and work as an executive at an a...,within a few hours,100%,40%,f,Boerum Hill,1.0,3.0,"['email', 'phone', 'work_email']",t,t,Neighborhood highlights,Boerum Hill,Brooklyn,40.684420,-73.980680,Private room in home,Private room,2,2.5,2.5 baths,5.0,5.0,"[""Portable fans"", ""Oven"", ""Baking sheet"", ""Fir...",$765.00,3,60,3.0,3.0,60.0,60.0,3.0,60.0,NaN,t,30,49,66,326,2025-03-02,43,0,0,267,0,0,0.0,2012-07-09,2023-08-30,4.70,4.83,4.52,4.88,4.88,4.86,4.62,OSE-STRREG-0001784,f,1,0,1,0,0.28
3,3,38833,city scrape,Spectacular West Harlem Garden Apt,This is a very large and unique space. An inc...,West Harlem is now packed with great restauran...,166532,Matthew,2010-07-14,"New York, NY",I have been a New Yorker for a long time\n and...,within an hour,100%,97%,t,Harlem,1.0,1.0,"['email', 'phone']",t,t,Neighborhood highlights,Harlem,Manhattan,40.818058,-73.946671,Entire home,Entire home/apt,2,1.0,1 bath,1.0,1.0,"[""Fire extinguisher"", ""Clothing storage: close...",$139.00,2,45,2.0,2.0,1125.0,1125.0,2.0,1125.0,NaN,t,7,18,25,25,2025-03-03,241,42,3,25,43,255,35445.0,2010-08-28,2025-02-21,4.85,4.87,4.50,4.96,4.96,4.79,4.82,OSE-STRREG-0000476,f,1,1,0,0,1.36
4,4,39282,city scrape,“Work-from-home” from OUR home.,*Monthly Discount will automatically apply <br...,THE NEIGHBORHOOD:<br />Our apartment is locate...,168525,Gustavo,2010-07-16,"New York, NY",I am a music producer. And my wife is a hair s...,within an hour,100%,100%,t,Williamsburg,2.0,2.0,"['email', 'phone']",t,t,Neighborhood highlights,Williamsburg,Brooklyn,40.710651,-73.950874,Private room in rental unit,Private room,2,1.0,1 shared bath,1.0,1.0,"[""Oven"", ""Rice maker"", ""Laundromat nearby"", ""L...",$130.00,4,45,4.0,4.0,45.0,45.0,4.0,45.0,NaN,t,14,22,38,38,2025-03-02,274,12,0,38,12,154,20020.0,2010-08-02,2025-01-03,4.82,4.83,4.61,4.94,4.88,4.85,4.78,OSE-STRREG-0001150,f,2,0,2,0,1.54

## 1.2 : 원본 데이터 shape 정보

In [23]:
# 원본 데이터 쉐이프
print('원본 데이터 쉐이프 정보')
print(bnb.shape)

원본 데이터 쉐이프 정보
(22308, 73)

## 1.3 : 원본 데이터 info 정보

In [24]:
# 원본 데이터 데이터프레임 인포
print('원본 데이터 인포')
print(bnb.info())

원본 데이터 인포
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22308 entries, 0 to 22307
Data columns (total 73 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Unnamed: 0                                    22308 non-null  int64
 1   id                                            22308 non-null  int64
 2   source                                        22308 non-null  object
 3   name                                          22308 non-null  object
 4   description                                   21903 non-null  object
 5   neighborhood_overview                         12262 non-null  object
 6   host_id                                       22308 non-null  int64
 7   host_name                                     22288 non-null  object
 8   host_since                                    22288 non-null  object
 9   host_location                                 17025 non-null  object
 10  host_about                                    13391 non-null  object
 11  host_response_time                            17915 non-null  object
 12  host_response_rate                            17915 non-null  object
 13  host_acceptance_rate                          18842 non-null  object
 14  host_is_superhost                             21934 non-null  object
 15  host_neighbourhood                            17578 non-null  object
 16  host_listings_count                           22288 non-null  float64
 17  host_total_listings_count                     22288 non-null  float64
 18  host_verifications                            22288 non-null  object
 19  host_has_profile_pic                          22288 non-null  object
 20  host_identity_verified                        22288 non-null  object
 21  neighbourhood                                 12262 non-null  object
 22  neighbourhood_cleansed                        22308 non-null  object
 23  neighbourhood_group_cleansed                  22308 non-null  object
 24  latitude                                      22308 non-null  float64
 25  longitude                                     22308 non-null  float64
 26  property_type                                 22308 non-null  object
 27  room_type                                     22308 non-null  object
 28  accommodates                                  22308 non-null  int64
 29  bathrooms                                     22302 non-null  float64
 30  bathrooms_text                                22294 non-null  object
 31  bedrooms                                      22259 non-null  float64
 32  beds                                          22229 non-null  float64
 33  amenities                                     22308 non-null  object
 34  price                                         22308 non-null  object
 35  minimum_nights                                22308 non-null  int64
 36  maximum_nights                                22308 non-null  int64
 37  minimum_minimum_nights                        22308 non-null  float64
 38  maximum_minimum_nights                        22308 non-null  float64
 39  minimum_maximum_nights                        22308 non-null  float64
 40  maximum_maximum_nights                        22308 non-null  float64
 41  minimum_nights_avg_ntm                        22308 non-null  float64
 42  maximum_nights_avg_ntm                        22308 non-null  float64
 43  calendar_updated                              0 non-null      float64
 44  has_availability                              22062 non-null  object
 45  availability_30                               22308 non-null  int64
 46  availability_60                               22308 non-null  int64
 47  availability_90                               22308 non-null  int64
 48  availability_365                              22308 non-null  int64
 49  calendar_last_scraped                         22308 non-null  object
 50  number_of_reviews                             22308 non-null  int64
 51  number_of_reviews_ltm                         22308 non-null  int64
 52  number_of_reviews_l30d                        22308 non-null  int64
 53  availability_eoy                              22308 non-null  int64
 54  number_of_reviews_ly                          22308 non-null  int64
 55  estimated_occupancy_l365d                     22308 non-null  int64
 56  estimated_revenue_l365d                       22308 non-null  float64
 57  first_review                                  15510 non-null  object
 58  last_review                                   15510 non-null  object
 59  review_scores_rating                          15510 non-null  float64
 60  review_scores_accuracy                        15510 non-null  float64
 61  review_scores_cleanliness                     15510 non-null  float64
 62  review_scores_checkin                         15510 non-null  float64
 63  review_scores_communication                   15510 non-null  float64
 64  review_scores_location                        15509 non-null  float64
 65  review_scores_value                           15510 non-null  float64
 66  license                                       4463 non-null   object
 67  instant_bookable                              22308 non-null  object
 68  calculated_host_listings_count                22308 non-null  int64
 69  calculated_host_listings_count_entire_homes   22308 non-null  int64
 70  calculated_host_listings_count_private_rooms  22308 non-null  int64
 71  calculated_host_listings_count_shared_rooms   22308 non-null  int64
 72  reviews_per_month                             15510 non-null  float64
dtypes: float64(23), int64(20), object(30)
memory usage: 12.4+ MB
None

##1.4 : 원본 데이터 결측치 확인

In [25]:
# 원본 데이터 결측치
print('원본 결측치')
print(bnb.isnull().sum())

원본 결측치
Unnamed: 0                                          0
id                                                  0
source                                              0
name                                                0
description                                       405
neighborhood_overview                           10046
host_id                                             0
host_name                                          20
host_since                                         20
host_location                                    5283
host_about                                       8917
host_response_time                               4393
host_response_rate                               4393
host_acceptance_rate                             3466
host_is_superhost                                 374
host_neighbourhood                               4730
host_listings_count                                20
host_total_listings_count                          20
host_verifications                                 20
host_has_profile_pic                               20
host_identity_verified                             20
neighbourhood                                   10046
neighbourhood_cleansed                              0
neighbourhood_group_cleansed                        0
latitude                                            0
longitude                                           0
property_type                                       0
room_type                                           0
accommodates                                        0
bathrooms                                           6
bathrooms_text                                     14
bedrooms                                           49
beds                                               79
amenities                                           0
price                                               0
minimum_nights                                      0
maximum_nights                                      0
minimum_minimum_nights                              0
maximum_minimum_nights                              0
minimum_maximum_nights                              0
maximum_maximum_nights                              0
minimum_nights_avg_ntm                              0
maximum_nights_avg_ntm                              0
calendar_updated                                22308
has_availability                                  246
availability_30                                     0
availability_60                                     0
availability_90                                     0
availability_365                                    0
calendar_last_scraped                               0
number_of_reviews                                   0
number_of_reviews_ltm                               0
number_of_reviews_l30d                              0
availability_eoy                                    0
number_of_reviews_ly                                0
estimated_occupancy_l365d                           0
estimated_revenue_l365d                             0
first_review                                     6798
last_review                                      6798
review_scores_rating                             6798
review_scores_accuracy                           6798
review_scores_cleanliness                        6798
review_scores_checkin                            6798
review_scores_communication                      6798
review_scores_location                           6799
review_scores_value                              6798
license                                         17845
instant_bookable                                    0
calculated_host_listings_count                      0
calculated_host_listings_count_entire_homes         0
calculated_host_listings_count_private_rooms        0
calculated_host_listings_count_shared_rooms         0
reviews_per_month                                6798
dtype: int64

## 1.5 : 원본 데이터 중복치 확인

In [26]:
# 원본 데이터 중복치
print('원본 데이터 중복치')
bnb.duplicated().sum()

원본 데이터 중복치

np.int64(0)

#  2. 데이터 전처리

## 2.1 : 데이터 형변환
|번호|컬럼명|변환 전|변환 후|
|---|---|---|---|
|1|price|object|float|
|2|host_response_rate|object|float|
|3|host_acceptance_rate|object|float|
|4|last_review|object|Datetime|
|5|host_since|object|Datetime|
|6|host_response_time|object|category|
|7|host_is_superhost|object|boolean|
|8|host_has_profile_pic|object|boolean|
|9|host_identity_verified|object|boolean|
|10|has_availability|object|boolean|
|11|instant_bookable|object|boolean|
|12|license|object|boolean|

### 2.1.1 : 타입 변환 ▶ float

In [27]:
# 1. 'price' -> float형 변환
bnb['price'] = (
    bnb['price']
    .astype(str)
    .str.replace('$', '', regex=False)
    .str.replace(',', '', regex=False)
    .astype(float)
)

# 2. 'host_response_rate' -> float형 변환
# 문자열에 '%'를 제거하고 100으로 나눠서 실수화함
bnb['host_response_rate'] = pd.to_numeric(
    bnb['host_response_rate'].replace('%', '', regex=True),
    errors='coerce'
) / 100

# 3. 'host_acceptance_rate' -> float형 변환
# 문자열에 '%'를 제거하고 100으로 나눠서 실수화함
bnb['host_acceptance_rate'] = pd.to_numeric(
    bnb['host_acceptance_rate'].replace('%', '', regex=True),
    errors='coerce'
) / 100

### 2.1.2 : 타입 변환 ▶ datetime

In [28]:
# 4. 'last_review' -> datetime형 변환
bnb['last_review'] = pd.to_datetime(bnb['last_review'], errors='coerce')

# 5. 'host_since' -> datetime형 변환
bnb['host_since'] = pd.to_datetime(bnb['host_since'], errors='coerce')

### 2.1.3 : 타입 변환 ▶ Category

In [29]:
# 6. 'host_response_time' -> 범주형으로 변환
bnb['host_response_time'] = bnb['host_response_time'].astype('category')

### 시간 단위(int)로 변환 해도 될듯
# ex)
# within an hour = 1
# within a few hours = 6
# within a day = 24

### 2.1.4 : 타입 변환 ▶ boolean

In [30]:
# 7~12  . 결과값이 't / f'인 5개의 컬럼을 Boolean으로 형변환
bool_cols = ['host_is_superhost', 'host_has_profile_pic', 'host_identity_verified',
              'has_availability', 'instant_bookable']

for col in bool_cols:
    bnb[col] = bnb[col].map({'t': True, 'f': False})


# 13. 'license' -> Boolean으로 형변환.
bnb['license'] = bnb['license'].notna()

## 2.2 결측치 처리

### 2.2.1 호스트 가입일 대체

In [31]:
# 호스트 가입일 결측값을 최초 리뷰일로 대체
bnb['host_since'] = bnb['host_since'].fillna(bnb['first_review'])

# 최초 리뷰일이 NaN인 관계로 가입일에 적용 불가한 데이터 삭제
bnb = bnb.dropna(subset=['host_since'])

# 삭제 확인
bnb['host_since'].isnull().sum()

np.int64(0)

### 2.2.2 호스트 거주지역 분류 대체

In [32]:
# 호스트 거주 지역을 주 or 국가별 분류


# host_location 구분자로 분할
host_loc = bnb['host_location'].str.split(',', expand=True)


# 비교군 county1, county2 컬럼 지정
county1 = host_loc.iloc[:, 0].str.strip()
county2 = host_loc.iloc[:, 1].str.strip()


# DataFrame화
county = pd.DataFrame({'city':county2,'local':county1})


# 대문자 변환으로 값 통일
county['local'] = county['local'].str.upper()
county['city'] = county['city'].str.upper()

county['host_neighbourhood'] = bnb['host_neighbourhood']


# 도시 이름 기준 location 변환
county.loc[county['local'] == 'NEW YORK', 'city'] = 'NY'
county.loc[county['local'] == 'DUBAI', 'city'] = 'UAE'
county.loc[county['local'] == 'LONDON', 'city'] = 'UK'
county.loc[county['local'] == 'SANTO DOMINGO', 'city'] = 'DOMINICA'
county.loc[county['local'] == 'WILLEMSTAD', 'city'] = 'CURACAO'
county.loc[county['local'] == 'PORT OF SPAIN', 'city'] = 'TRINIDAD TOBAGO'
county.loc[county['local'] == 'PIARCO', 'city'] = 'TRINIDAD TOBAGO'
county.loc[county['local'] == 'BRAZIL', 'city'] = 'BRAZIL'
county.loc[county['local'] == 'JAMAICA', 'city'] = 'JAMAICA'
county.loc[county['local'] == 'HONG KONG', 'city'] = 'HONG KONG'
county.loc[county['local'] == 'ISRAEL', 'city'] = 'ISRAEL'
county.loc[county['local'] == 'MEXICO', 'city'] = 'MEXICO'
county.loc[county['local'] == 'COLOMBIA', 'city'] = 'COLOMBIA'
county.loc[county['local'] == 'DOMINICAN REPUBLIC', 'city'] = 'DOMINICA'
county.loc[county['local'] == 'GERMANY', 'city'] = 'GERMANY'
county.loc[county['local'] == 'SINGAPORE', 'city'] = 'SINGAPORE'
county.loc[county['local'] == 'NEW JERSEY', 'city'] = 'NJ'
county.loc[county['local'] == 'MAINE', 'city'] = 'ME'
county.loc[county['local'] == 'MASSACHUSETTS', 'city'] = 'MA'
county.loc[county['local'] == 'FLORIDA', 'city'] = 'FL'
county.loc[county['local'] == 'CONNECTICUT', 'city'] = 'CT'
county.loc[county['local'] == 'VERMONT', 'city'] = 'VT'
county.loc[county['local'] == 'UTAH', 'city'] = 'UT'
county.loc[county['local'] == 'OREGON', 'city'] = 'OT'
county.loc[county['local'] == 'HAWAII', 'city'] = 'HI'
county.loc[county['local'] == 'CALIFORNIA', 'city'] = 'CA'
county.loc[county['local'] == 'MISSOURI', 'city'] = 'MO'
county.loc[county['local'] == 'GEORGIA', 'city'] = 'GA'


# 구글링을 통한 지역 매칭 기준
county.loc[county['host_neighbourhood'] == 'Elmhurst', 'city'] = 'NY'
county.loc[county['host_neighbourhood'] == 'Harlem', 'city'] = 'NY'
county.loc[county['host_neighbourhood'] == 'West Bronx', 'city'] = 'NY'
county.loc[county['host_neighbourhood'] == 'Bushwick', 'city'] = 'NY'
county.loc[county['host_neighbourhood'] == 'St Kilda East', 'city'] = 'NY'
county.loc[county['host_neighbourhood'] == "Hell's Kitchen", 'city'] = 'NY'
county.loc[county['host_neighbourhood'] == 'Bedford-Stuyvesant', 'city'] = 'NY'
county.loc[county['host_neighbourhood'] == 'East New York', 'city'] = 'NY'
county.loc[county['host_neighbourhood'] == 'Chelsea', 'city'] = 'NY'
county.loc[county['host_neighbourhood'] == 'Park Slope', 'city'] = 'NY'
county.loc[county['host_neighbourhood'] == 'Gowanus', 'city'] = 'NY'
county.loc[county['host_neighbourhood'] == 'Sheepshead Bay', 'city'] = 'NY'
county.loc[county['host_neighbourhood'] == 'Lefferts Garden', 'city'] = 'NY'
county.loc[county['host_neighbourhood'] == 'Flatiron District', 'city'] = 'NY'
county.loc[county['host_neighbourhood'] == "Prince's Bay", 'city'] = 'NY'
county.loc[county['host_neighbourhood'] == "West Village", 'city'] = 'NY'
county.loc[county['host_neighbourhood'] == "Lefferts Manor Historic District", 'city'] = 'NY'
county.loc[county['host_neighbourhood'] == "Flushing", 'city'] = 'NY'
county.loc[county['host_neighbourhood'] == "East Flatbush", 'city'] = 'NY'
county.loc[county['host_neighbourhood'] == 'Williamsburg', 'city'] = 'VA'
county.loc[county['host_neighbourhood'] == 'Little Haiti', 'city'] = 'FL'
county.loc[county['host_neighbourhood'] == 'Waikiki', 'city'] = 'HI'
county.loc[county['host_neighbourhood'] == 'Astoria', 'city'] = 'OR'
county.loc[county['host_neighbourhood'] == 'Civic Center', 'city'] = 'CA'
county.loc[county['host_neighbourhood'] == 'East Rock', 'city'] = 'CT'
county.loc[county['host_neighbourhood'] == 'Pine Hills', 'city'] = 'FL'


# 동네 기준 매칭 딕셔너리 생성
region_state_map = {
    "Jamaica": "NY",
    "Gateway District": "FL",
    "Crown Heights": "NY",
    "Woodside": "NY",
    "Ocean Hill": "NY",
    "Long Island City": "NY",
    "Brickell": "FL",
    "Canarsie": "NY",
    "Clearwater Beach": "FL",
    "East Bronx": "NY",
    "Flatbush": "NY",
    "Fort Hamilton": "NY",
    "Arverne": "NY",
    "Greenpoint": "NY",
    "Cypress Hills": "NY",
    "Far Rockaway": "NY",
    "Brooklyn Heights": "NY",
    "Little Caribbean": "NY",
    "Midtown": "NY",
    "North Beach": "NY",
    "Hollywood South Central Beach": "CA",
    "Southside": "DC",
    "Mott Haven": "NY",
    "Flatlands": "NY",
    "Sunset Park": "NY",
    "Central Business District": "NY",
    "Upper East Side": "NY",
    "Bay Ridge": "NY",
    "Hamilton Heights": "NY",
    "Clinton Hill": "NY",
    "Midtown East": "NY",
    "Boerum Hill": "NY",
    "Concourse Village": "NY",
    "North City": "MO",
    "South Beach": "FL",
    "Fort Greene": "NY",
    "Sunnyside": "NY",
    "Upper West Side": "NY",
    "Midwood": "NY",
    "Brighton Beach": "NY",
    "Gramercy Park": "NY",
    "Corona": "NY",
    "Van Nest": "NY",
    "East Harlem": "NY",
    "Mid Island": "NY",
    "Chinatown": "NY",
    "Queens Village": "NY",
    "Sturbridge": "MA",
    "Clason Point": "NY",
    "Williamsbridge": "NY",
    "Stuyvesant Heights": "NY",
    "Brownsville": "NY",
    "Guilford Hills": "NC",
    "Woodstock": "NY",
    "Rockaway Beach": "NY",
    "Edenwald": "NY",
    "Hunts Point": "NY",
    "Prospect Heights": "NY",
    "Washington Heights": "NY",
    "Bergen Beach": "NY",
    "Ditmars Steinway": "NY",
    "Mill Basin": "NY",
    "Murray Hill": "NY",
    "East Elmhurst": "NY",
    "Union Square": "NY",
    "Ridgewood": "NY",
    "Laconia": "NH",
    "Pelham Gardens": "NY",
    "Kensington": "NY",
    "Mariners Harbor": "NY",
    "Port Richmond": "NY",
    "West Brighton": "NY",
    "Lindenwood": "NY",
    "The Rockaways": "NY",
    "Midland Beach": "NY",
    "Center City West": "PA",
    "Prospect Lefferts Gardens": "NY",
    "Morris Park": "NY",
    "Morrisania": "NY",
    "Maspeth": "NY",
    "Cobble Hill": "NY",
    "Gravesend": "NY",
    "Claremont": "NY",
    "Bridge Plaza": "NY",
    "Downtown Los Angeles": "CA",
    "Bath Beach": "NY",
    "Forest Hills": "NY",
    "Lower East Side": "NY",
    "St. Albans": "NY",
    "Rego Park": "NY",
    "Norwood": "NY",
    "Baychester": "NY",
    "Highbridge": "NY",
    "Pelham Bay": "NY",
    "East Village": "NY",
    "Rosebank": "NY",
    "Bensonhurst": "NY",
    "Alphabet City": "NY",
    "Concourse": "NY",
    "Eltingville": "NY",
    "Nolita": "NY",
    "Greenwich Village": "NY",
    "Richmond Hill": "NY",
    "Jackson Heights": "NY",
    "Wakefield": "NY",
    "Carroll Gardens": "NY",
    "Little Italy": "NY",
    "Dongan Hills": "NY",
    "Central City": "CO",
    "Elm Park": "MA",
    "Belmont": "NY",
    "Coney Island": "NY",
    "Red Hook": "NY",
    "Allerton": "NY",
    "Marine Park": "NY",
    "Manhattan Beach": "NY",
    "Fordham Heights": "NY",
    "Fordham Manor": "NY",
    "Antioch": "CA",
    "Morris Heights": "NY",
    "Glendale": "NY",
    "Inwood": "NY",
    "New Springville": "NY",
    "Kips Bay": "NY",
    "Morningside Heights": "NY",
    "Sylvan Heights": "NC",
    "Highlands": "NJ",
    "Shore Acres": "OR",
    "Randall Manor": "NY",
    "South Ozone Park": "NY",
    "Westchester Square": "NY",
    "El Mamey": "Dominica",
    "Southpoint": "NC",
    "Rossville": "NY",
    "Bulls Head": "NY",
    "Gerritsen Beach": "NY",
    "Spring Creek": "NY",
    "Downtown Brooklyn": "NY",
    "Journal Square": "NJ",
    "City Island": "NY",
    "Todt Hill": "NY",
    "Homecrest": "NY",
    "Parkchester": "NY",
    "Hollis": "NY",
    "Manor Heights": "NY",
    "Throgs Neck": "NY",
    "Utopia": "NY",
    "Borough Park": "NY",
    "Wilshire Montana": "CA",
    "College Park, MD": "MD",
    "Ozone Park": "NY",
    "Soho": "NY",
    "Times Square/Theatre District": "NY",
    "Tribeca": "NY",
    "Pacific Heights": "CA",
    "West Farms": "NY",
    "Rockaway Park": "NY",
    "Garrison": "NY",
    "Whitestone": "NY",
    "Briarwood": "NY",
    "Silver Lake": "CA",
    "Echo Park": "CA",
    "Mount Eden": "NY",
    "Miami Beach": "FL",
    "Tottenville": "NY",
    "University Heights": "NY",
    "Springfield Gardens": "NY",
    "Fresh Meadows": "NY",
    "Central LA": "CA",
    "South Jamesport": "NY",
    "French Quarter": "LA",
    "Downtown Miami": "FL",
    "Travis - Chelsea": "NY",
    "North Riverdale": "NY",
    "Concord": "CA",
    "La Jolla": "CA",
    "Windsor Terrace": "NY",
    "Oakwood": "NY",
    "New Brighton": "NY",
    "Bayside": "NY",
    "Arrochar": "NY",
    "Dutch Kills": "NY",
    "Cabo Branco": "Brazil",
    "East Williamsburg": "NY",
    "Downtown Jersey City": "NJ",
    "College Point": "NY",
    "Kew Gardens": "NY",
    "Edgewater": "NJ",
    "Oakland Gardens": "NY",
    "Brighton": "MA",
    "South Philadelphia": "PA",
    "Washington Square West": "PA",
    "Spuyten Duyvil": "NY",
    "Highland Lakes": "NJ",
    "Central Ward": "NJ",
    "Lazybrook / Timbergrove": "TX",
    "Mile Square": "CT",
    "Riverdale": "NY",
    "South Richmond Hill": "NY",
    "Downtown": "NY",
    "West Dover": "VT",
    "Elizabethport": "NJ",
    "South Slope": "NY",
    "Colgate Center": "NY",
    "South Side": "IL"
}


# 동네 기준 매핑 적용
county['region_code'] = county['host_neighbourhood'].map(region_state_map)


# 동네 기준 매칭 적용
county['city'] = county['city'].fillna(county['region_code'])


# bnb 데이터에 가공 데이터 변경
bnb['host_location'] = county['city']

### 2.2.3 불필요 컬럼 삭제

In [33]:
# 불필요한 컬럼 삭제
cols_to_drop = [
    'neighborhood_overview',
    'description',
    'host_name',
    'neighbourhood',
    'minimum_minimum_nights',
    'maximum_minimum_nights',
    'minimum_maximum_nights',
    'maximum_maximum_nights',
    'calendar_updated',
    'calendar_last_scraped',
    'host_verifications'
]

# 삭제 전 컬럼 개수
before_cols = bnb.shape[1]

# 컬럼 삭제
bnb = bnb.drop(columns=cols_to_drop)

# 삭제 후 컬럼 개수
after_cols = bnb.shape[1]

print(f"컬럼 삭제 완료: {before_cols - after_cols}개 컬럼 제거됨")
print(f"삭제 전: {before_cols}개 -> 삭제 후: {after_cols}개")

컬럼 삭제 완료: 11개 컬럼 제거됨
삭제 전: 73개 -> 삭제 후: 62개

### 2.2.4 숙박일 구간화

In [34]:
bins = [0, 29, 89, 181, 365, np.inf]
labels = ['Days', 'Months', 'Quarter', 'Half year', 'Annual']


# minimum_nights 구간화
bnb['min_nights_group'] = pd.cut(
    bnb['minimum_nights'],
    bins=bins,
    labels=labels,
    right=True
)


# maximum_nights 구간화(minimum_nights 기준과 동일)
bnb['max_nights_group'] = pd.cut(
    bnb['maximum_nights'],
    bins=bins,
    labels=labels,
    right=True
)


# 구간별 분포 확인
print("minimum_nights 그룹별 분포:")
print(bnb['min_nights_group'].value_counts())

print("\nmaximum_nights 그룹별 분포:")
print(bnb['max_nights_group'].value_counts())

minimum_nights 그룹별 분포:
min_nights_group
Months       17642
Days          4365
Quarter        215
Half year       53
Annual          30
Name: count, dtype: int64

maximum_nights 그룹별 분포:
max_nights_group
Half year    9561
Annual       6145
Months       2709
Quarter      2633
Days         1257
Name: count, dtype: int64

### 2.2.5 파생변수 생성

In [35]:
# Host 숙소 소개글의 작성길이 파악 위해 글자 수 추출
bnb['host_about'] = bnb['host_about'].fillna('')

host_about_len = bnb['host_about'].str.len()

bnb.insert(11,'host_about_len',host_about_len)

In [36]:
# 2. 리뷰 존재 여부 컬럼 생성(True / False)
bnb['has_review'] = bnb['number_of_reviews'] > 0