In [ ]:
# import usage libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import os

# 시각화 OS별 한글폰트 설정
if os.name == 'nt':
    plt.rcParams['font.family'] = 'Malgun Gothic'  # Windows 폰트 설정
elif os.name == 'posix':
    plt.rcParams['font.family'] = 'AppleGothic'  # Mac 폰트 설정

pd.set_option('display.max_columns', 100)      # 컬럼 축약 생략 코드 (None ~ 숫자)
pd.set_option('display.max_rows', 50)    # 시리즈 행 축약 생략 코드 (None ~ 숫자)

bnb = pd.read_csv('2025_Airbnb_NYC_listings.csv')

In [63]:
bnb[bnb['first_review'].isnull()]

,Unnamed: 0,id,source,name,description,neighborhood_overview,host_id,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,availability_eoy,number_of_reviews_ly,estimated_occupancy_l365d,estimated_revenue_l365d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
31,41,45935,city scrape,Room in Beautiful Townhouse.,Single bedroom available in 3 bedroom apartmen...,NaN,204586,L,2010-08-17,NaN,NaN,NaN,NaN,NaN,f,NaN,1.0,2.0,"['email', 'phone']",t,t,NaN,Mott Haven,Bronx,40.806350,-73.922010,Private room in rental unit,Private room,1,1.0,1 shared bath,1.0,1.0,"[""Fire extinguisher"", ""First aid kit"", ""Breakf...",$60.00,30,40,30.0,30.0,40.0,40.0,30.0,40.0,NaN,t,24,54,83,83,2025-03-02,0,0,0,83,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,1,0,1,0,NaN
59,78,54466,city scrape,Beautiful Uptown Manhattan apartmnt,NaN,NaN,253385,Douglas,2010-10-05,"New York, NY",NaN,NaN,NaN,NaN,f,Harlem,1.0,1.0,"['email', 'phone']",t,t,NaN,Harlem,Manhattan,40.802550,-73.958030,Private room in rental unit,Private room,2,1.0,1 bath,1.0,1.0,"[""TV with standard cable"", ""Oven"", ""Gym"", ""Dis...",$172.00,30,60,30.0,30.0,60.0,60.0,30.0,60.0,NaN,t,30,60,90,365,2025-03-02,0,0,0,305,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
107,150,63588,city scrape,LL3,A large bedroom sleeps 3 in a modern 2 bedroom...,My home sits on a tree lined street across fro...,295128,Carol Gloria,2010-11-22,"New York, NY",I'm a world traveler and a retired customer s...,NaN,NaN,NaN,f,Soundview,6.0,7.0,"['email', 'phone']",t,t,Neighborhood highlights,Clason Point,Bronx,40.811610,-73.854990,Private room in home,Private room,3,1.0,1 shared bath,2.0,2.0,"[""Oven"", ""Fire extinguisher"", ""First aid kit"",...",$107.00,30,1125,30.0,30.0,1125.0,1125.0,30.0,1125.0,NaN,t,0,0,0,0,2025-03-03,0,0,0,0,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,6,0,6,0,NaN
110,154,169483,city scrape,Very close to Downtown Awesome Private Apartment,"Experience NY just like a local, clean, comfor...",Right by the F line<br />No walking needed,807642,Jeffrey,2011-07-11,"New York, NY",Hi there! I have lived in New York for 19 year...,NaN,NaN,NaN,f,Gravesend,2.0,2.0,"['email', 'phone']",t,t,Neighborhood highlights,Gravesend,Brooklyn,40.606020,-73.970760,Entire rental unit,Entire home/apt,4,1.0,1 bath,1.0,1.0,"[""TV with standard cable"", ""Kitchen"", ""First a...",$231.00,30,30,30.0,30.0,1125.0,1125.0,30.0,1125.0,NaN,t,0,0,0,182,2025-03-02,0,0,0,122,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,2,1,1,0,NaN
189,288,89427,city scrape,The Brooklyn Waverly,NaN,NaN,116599,Sahr,2010-05-01,"New York, NY",Greetings! I am a working mother and artist wh...,NaN,NaN,NaN,f,Clinton Hill,3.0,5.0,"['email', 'phone']",t,t,NaN,Clinton Hill,Brooklyn,40.685130,-73.966480,Entire rental unit,Entire home/apt,10,1.5,1.5 baths,1.0,0.0,"[""TV with standard cable"", ""Outdoor furniture""...",$800.00,30,365,30.0,30.0,365.0,365.0,30.0,365.0,NaN,t,23,53,83,358,2025-03-02,0,0,0,298,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,3,1,2,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22303,37429,1366333532374850165,city scrape,Beautiful 1-Bed Apt in Harlem!,Welcome to your temporary home in the vibrant ...,NaN,40019013,Cecilia,2015-07-30,"New York, NY",NaN,NaN,NaN,NaN,f,NaN,1.0,2.0,"['email', 'phone']",t,t,NaN,Harlem,Manhattan,40.813794,-73.952399,Private room in rental unit,Private room,1,1.0,1 shared bath,1.0,1.0,"[""Air conditioning"", ""Carbon monoxide alarm"", ...",$72.00,30,365,30.0,30.0,365.0,365.0,30.0,365.0,NaN,t,23,53,83,358,2025-03-02,0,0,0,298,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,1,0,1,0,NaN
22304,37430,1366717321390111215,city scrape,Private Room w/ Ensuite Bath H,Stylish Private Rooms w/ En-Suite Baths in Bro...,NaN,483056418,Kristina,2022-10-10,"New York, NY",Are you tired of the tedious and time-consumin...,within an hour,100%,80%,t,Bedford-Stuyvesant,24.0,33.0,"['email', 'phone']",t,t,NaN,Bedford-Stuyvesant,Brooklyn,40.685500,-73.919510,Private room in rental unit,Private room,2,1.0,1 private bath,1.0,0.0,"[""Air conditioning"", ""Carbon monoxide alarm"", ...",$58.00,30,365,30.0,30.0,365.0,365.0,30.0,365.0,NaN,t,28,58,88,363,2025-03-02,0,0,0,303,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,24,0,24,0,NaN
22305,37431,1366721904709517353,city scrape,2 Bedroom on East Side,Located in the Murray Hill area and occupies a...,NaN,30283594,Global Luxury Suites,2015-03-30,"Hawthorne, NJ",NaN,within an hour,94%,99%,f,Miami Beach,619.0,1974.0,"['email', 'phone', 'work_email']",t,t,NaN,Kips Bay,Manhattan,40.745290,-73.979380,Entire rental unit,Entire home/apt,5,2.0,2 baths,2.0,3.0,"[""Air conditioning"", ""Carbon monoxide alarm"", ...",$299.00,30,365,30.0,30.0,365.0,365.0,30.0,365.0,NaN,t,30,39,39,99,2025-03-02,0,0,0,39,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,48,48,0,0,NaN
22306,37432,1366722692755341871,city scrape,Stylish 2Bd near Bryant Park,Enjoy everything the city has to offer while l...,NaN,407304997,Boomerang,2021-06-15,"New York, NY","At Boomerang, we believe in the idea ""you get ...",within an hour,89%,100%,f,Park Slope,26.0,38.0,"['email', 'phone']",t,t,NaN,Theater District,Manhattan,40.757133,-73.983124,Entire rental unit,Entire home/apt,4,1.0,1 bath,2.0,2.0,"[""Oven"", ""Gym"", ""Blender"", ""Dedicated workspac...",$200.00,30,365,30.0,30.0,365.0,365.0,30.0,365.0,NaN,t,30,60,90,365,2025-03-02,0,0,0,305,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,25,25,0,0,NaN
22307,37433,1366723228243064949,city scrape,Modern Private Room + Bath H,Stylish Private Rooms w/ En-Suite Baths in Bro...,NaN,483056418,Kristina,2022-10-10,"New York, NY",Are you tired of the tedious and time-consumin...,within an hour,100%,80%,t,Bedford-Stuyvesant,24.0,33.0,"['email', 'phone']",t,t,NaN,Bedford-Stuyvesant,Brooklyn,40.685500,-73.919510,Private room in rental unit,Private room,2,1.0,1 private bath,1.0,0.0,"[""Air conditioning"", ""Carbon monoxide alarm"", ...",$58.00,30,365,30.0,30.0,365.0,365.0,30.0,365.0,NaN,t,28,58,88,363,2025-03-02,0,0,0,303,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,24,0,24,0,NaN

In [64]:
# 데이터프레임 쉐이프
print('bnb 쉐이프 정보')
print(bnb.shape)

bnb 쉐이프 정보
(22308, 73)

In [65]:
# 데이터프레임 인포
print('bnb 인포')
print(bnb.info())

bnb 인포
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22308 entries, 0 to 22307
Data columns (total 73 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Unnamed: 0                                    22308 non-null  int64
 1   id                                            22308 non-null  int64
 2   source                                        22308 non-null  object
 3   name                                          22308 non-null  object
 4   description                                   21903 non-null  object
 5   neighborhood_overview                         12262 non-null  object
 6   host_id                                       22308 non-null  int64
 7   host_name                                     22288 non-null  object
 8   host_since                                    22288 non-null  object
 9   host_location                                 17025 non-null  object
 10  host_about                                    13391 non-null  object
 11  host_response_time                            17915 non-null  object
 12  host_response_rate                            17915 non-null  object
 13  host_acceptance_rate                          18842 non-null  object
 14  host_is_superhost                             21934 non-null  object
 15  host_neighbourhood                            17578 non-null  object
 16  host_listings_count                           22288 non-null  float64
 17  host_total_listings_count                     22288 non-null  float64
 18  host_verifications                            22288 non-null  object
 19  host_has_profile_pic                          22288 non-null  object
 20  host_identity_verified                        22288 non-null  object
 21  neighbourhood                                 12262 non-null  object
 22  neighbourhood_cleansed                        22308 non-null  object
 23  neighbourhood_group_cleansed                  22308 non-null  object
 24  latitude                                      22308 non-null  float64
 25  longitude                                     22308 non-null  float64
 26  property_type                                 22308 non-null  object
 27  room_type                                     22308 non-null  object
 28  accommodates                                  22308 non-null  int64
 29  bathrooms                                     22302 non-null  float64
 30  bathrooms_text                                22294 non-null  object
 31  bedrooms                                      22259 non-null  float64
 32  beds                                          22229 non-null  float64
 33  amenities                                     22308 non-null  object
 34  price                                         22308 non-null  object
 35  minimum_nights                                22308 non-null  int64
 36  maximum_nights                                22308 non-null  int64
 37  minimum_minimum_nights                        22308 non-null  float64
 38  maximum_minimum_nights                        22308 non-null  float64
 39  minimum_maximum_nights                        22308 non-null  float64
 40  maximum_maximum_nights                        22308 non-null  float64
 41  minimum_nights_avg_ntm                        22308 non-null  float64
 42  maximum_nights_avg_ntm                        22308 non-null  float64
 43  calendar_updated                              0 non-null      float64
 44  has_availability                              22062 non-null  object
 45  availability_30                               22308 non-null  int64
 46  availability_60                               22308 non-null  int64
 47  availability_90                               22308 non-null  int64
 48  availability_365                              22308 non-null  int64
 49  calendar_last_scraped                         22308 non-null  object
 50  number_of_reviews                             22308 non-null  int64
 51  number_of_reviews_ltm                         22308 non-null  int64
 52  number_of_reviews_l30d                        22308 non-null  int64
 53  availability_eoy                              22308 non-null  int64
 54  number_of_reviews_ly                          22308 non-null  int64
 55  estimated_occupancy_l365d                     22308 non-null  int64
 56  estimated_revenue_l365d                       22308 non-null  float64
 57  first_review                                  15510 non-null  object
 58  last_review                                   15510 non-null  object
 59  review_scores_rating                          15510 non-null  float64
 60  review_scores_accuracy                        15510 non-null  float64
 61  review_scores_cleanliness                     15510 non-null  float64
 62  review_scores_checkin                         15510 non-null  float64
 63  review_scores_communication                   15510 non-null  float64
 64  review_scores_location                        15509 non-null  float64
 65  review_scores_value                           15510 non-null  float64
 66  license                                       4463 non-null   object
 67  instant_bookable                              22308 non-null  object
 68  calculated_host_listings_count                22308 non-null  int64
 69  calculated_host_listings_count_entire_homes   22308 non-null  int64
 70  calculated_host_listings_count_private_rooms  22308 non-null  int64
 71  calculated_host_listings_count_shared_rooms   22308 non-null  int64
 72  reviews_per_month                             15510 non-null  float64
dtypes: float64(23), int64(20), object(30)
memory usage: 12.4+ MB
None

In [66]:
# 데이터프레임 결측치
print('bnb 결측치')
print(bnb.isnull().sum())

bnb 결측치
Unnamed: 0                                         0
id                                                 0
source                                             0
name                                               0
description                                      405
                                                ...
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
calculated_host_listings_count_shared_rooms        0
reviews_per_month                               6798
Length: 73, dtype: int64

In [67]:
# 데이터프레임 중복치
print('bnb 중복치')
bnb.duplicated().sum()

bnb 중복치

np.int64(0)

In [68]:
bnb['bathrooms_text'].value_counts()

bathrooms_text
1 bath               11281
1 shared bath         3939
1 private bath        2275
2 baths               1919
2 shared baths         686
1.5 baths              602
1.5 shared baths       355
0 shared baths         350
2.5 baths              216
3 baths                213
0 baths                 76
3 shared baths          70
3.5 baths               68
4 baths                 63
4 shared baths          27
Half-bath               25
4.5 baths               24
2.5 shared baths        22
Private half-bath       21
5 baths                 14
Shared half-bath        11
5 shared baths           9
6 baths                  9
3.5 shared baths         5
5.5 baths                5
7.5 baths                3
6 shared baths           2
15.5 baths               1
10.5 baths               1
7 baths                  1
4.5 shared baths         1
Name: count, dtype: int64

In [69]:
bnb['bathrooms'].value_counts()

bathrooms
1.0     17496
2.0      2605
1.5       957
0.0       434
3.0       283
2.5       237
4.0        91
3.5        72
0.5        57
4.5        25
5.0        23
6.0        11
5.5         5
7.5         3
10.5        1
15.5        1
7.0         1
Name: count, dtype: int64

In [70]:
bnb['host_verifications'].value_counts()

host_verifications
['email', 'phone']                  16852
['email', 'phone', 'work_email']     3230
['phone']                            2138
['phone', 'work_email']                60
['email']                               6
[]                                      2
Name: count, dtype: int64

In [71]:
bnb['availability_30'].value_counts()

availability_30
0     5519
30    4898
29    2670
28    1339
1      906
23     645
27     634
2      438
5      275
4      269
16     266
3      263
6      261
18     250
13     240
7      236
15     236
24     234
9      231
26     231
8      230
17     224
14     220
10     215
12     211
21     203
11     197
22     196
19     195
20     190
25     186
Name: count, dtype: int64

In [72]:
bnb['availability_60'].value_counts()

availability_60
60    4585
0     3514
59    2514
58    1189
30     595
      ...
10     116
39     114
41     111
49     109
45     107
Name: count, Length: 61, dtype: int64

In [73]:
bnb['availability_90'].value_counts()

availability_90
90    4387
0     2421
89    2410
88    1153
83     508
      ...
4       81
51      80
67      77
65      71
72      70
Name: count, Length: 91, dtype: int64

In [74]:
bnb['availability_365'].value_counts()

availability_365
365    2783
364    1136
363     713
269     540
90      445
       ...
4         9
12        8
14        7
7         6
22        6
Name: count, Length: 366, dtype: int64

In [75]:
bnb[bnb['host_id']==107434423].head()

,Unnamed: 0,id,source,name,description,neighborhood_overview,host_id,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,availability_eoy,number_of_reviews_ly,estimated_occupancy_l365d,estimated_revenue_l365d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
3042,9214,20845031,city scrape,"Blueground | Midtown E, gym, doorman, nr the 6",Show up and start living from day one in Midto...,This furnished property is situated in Kips Ba...,107434423,Blueground,2016-12-16,"New York, NY","We’re Blueground, a global proptech company wi...",within an hour,100%,97%,f,Cambridge,5255.0,5458.0,"['email', 'phone', 'work_email']",t,t,Neighborhood highlights,Kips Bay,Manhattan,40.745723,-73.979862,Entire rental unit,Entire home/apt,2,1.0,1 bath,1.0,1.0,"[""Oven"", ""Gym"", ""Cooking basics"", ""Microwave"",...",$435.00,31,1125,31.0,337.0,1125.0,1125.0,38.1,1125.0,NaN,t,28,58,88,363,2025-03-02,0,0,0,303,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,1194,1194,0,0,NaN
3403,10400,23538486,city scrape,"Blueground | Park Ave, gym, doorman, in Midtown","Discover the best of Midtown, with this one be...",This furnished apartment is located in Murray ...,107434423,Blueground,2016-12-16,"New York, NY","We’re Blueground, a global proptech company wi...",within an hour,100%,97%,f,Cambridge,5255.0,5458.0,"['email', 'phone', 'work_email']",t,t,Neighborhood highlights,Murray Hill,Manhattan,40.748410,-73.979870,Entire rental unit,Entire home/apt,2,1.0,1 bath,1.0,1.0,"[""Oven"", ""Gym"", ""Cooking basics"", ""Microwave"",...",$348.00,31,1125,31.0,31.0,1125.0,1125.0,31.0,1125.0,NaN,t,0,0,0,1,2025-03-02,1,0,0,1,0,0,0.0,2019-01-15,2019-01-15,5.0,5.0,5.0,5.0,5.0,5.0,5.0,NaN,t,1194,1194,0,0,0.01
3490,10614,24535218,city scrape,"Blueground | Tribeca, gym, doorman & roof deck",Feel at home wherever you choose to live with ...,This furnished apartment is in the vibrant nei...,107434423,Blueground,2016-12-16,"New York, NY","We’re Blueground, a global proptech company wi...",within an hour,100%,97%,f,Cambridge,5255.0,5458.0,"['email', 'phone', 'work_email']",t,t,Neighborhood highlights,Tribeca,Manhattan,40.713833,-74.010242,Entire rental unit,Entire home/apt,2,1.0,1 bath,1.0,1.0,"[""Oven"", ""Cooking basics"", ""Microwave"", ""Crib""...",$388.00,31,1125,31.0,335.0,1125.0,1125.0,38.1,1125.0,NaN,t,0,1,31,306,2025-03-02,1,0,0,246,0,0,0.0,2021-05-29,2021-05-29,2.0,3.0,4.0,3.0,2.0,4.0,2.0,NaN,t,1194,1194,0,0,0.02
3502,10649,24960138,city scrape,"Blueground | Tribeca, indoor pool & gym",Show up and start living from day one in Downt...,This furnished apartment is in the vibrant nei...,107434423,Blueground,2016-12-16,"New York, NY","We’re Blueground, a global proptech company wi...",within an hour,100%,97%,f,Cambridge,5255.0,5458.0,"['email', 'phone', 'work_email']",t,t,Neighborhood highlights,Tribeca,Manhattan,40.715790,-74.005870,Entire rental unit,Entire home/apt,2,1.0,1 bath,0.0,1.0,"[""Oven"", ""Gym"", ""Cooking basics"", ""Microwave"",...",$357.00,31,1125,31.0,334.0,1125.0,1125.0,41.2,1125.0,NaN,t,0,0,0,235,2025-03-02,0,0,0,175,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,1194,1194,0,0,NaN
3594,10847,25823670,city scrape,"Blueground | UES, balcony, gym & doorman","Discover the best of Uptown, with this studio ...",This furnished property is located on the Uppe...,107434423,Blueground,2016-12-16,"New York, NY","We’re Blueground, a global proptech company wi...",within an hour,100%,97%,f,Cambridge,5255.0,5458.0,"['email', 'phone', 'work_email']",t,t,Neighborhood highlights,Upper East Side,Manhattan,40.775950,-73.955590,Entire rental unit,Entire home/apt,2,1.0,1 bath,0.0,1.0,"[""Oven"", ""Gym"", ""Cooking basics"", ""Microwave"",...",$288.00,31,1125,31.0,335.0,1125.0,1125.0,40.4,1125.0,NaN,t,0,11,41,316,2025-03-02,1,0,0,256,0,0,0.0,2019-02-28,2019-02-28,5.0,5.0,5.0,5.0,5.0,5.0,5.0,NaN,t,1194,1194,0,0,0.01

In [76]:
bnb['host_id'].value_counts()

host_id
107434423    1094
446820235     310
533234561     291
162280872     228
501999278     197
             ...
445134208       1
2384958         1
358641758       1
16395591        1
679189152       1
Name: count, Length: 10934, dtype: int64

In [77]:
# Host 숙소 소개글의 작성길이 파악 위해 글자 수 추출
bnb['host_about'] = bnb['host_about'].fillna('')

host_about_len = bnb['host_about'].str.len()

bnb.insert(11,'host_about_len',host_about_len)

In [78]:
# 호스트 가입일 결측값을 최초 리뷰일로 대체
bnb['host_since'] = bnb['host_since'].fillna(bnb['first_review'])

# 최초 리뷰일이 NaN인 관계로 가입일에 적용 불가한 데이터 삭제
bnb = bnb.dropna(subset=['host_since'])

# 삭제 확인
bnb['host_since'].isnull().sum()

np.int64(0)

In [88]:
bnb['first_review']
print('중앙값')
print(bnb[['review_scores_rating','review_scores_accuracy','review_scores_cleanliness','review_scores_checkin','review_scores_communication','review_scores_location','review_scores_value']].median())
print()
print('평균')
print(round(bnb[['review_scores_rating','review_scores_accuracy','review_scores_cleanliness','review_scores_checkin','review_scores_communication','review_scores_location','review_scores_value']].mean(),2))

중앙값
review_scores_rating           4.85
review_scores_accuracy         4.88
review_scores_cleanliness      4.83
review_scores_checkin          4.94
review_scores_communication    4.94
review_scores_location         4.82
review_scores_value            4.75
dtype: float64

평균
review_scores_rating           4.72
review_scores_accuracy         4.75
review_scores_cleanliness      4.69
review_scores_checkin          4.83
review_scores_communication    4.81
review_scores_location         4.73
review_scores_value            4.61
dtype: float64

In [96]:
bnb.iloc[17:18]

,Unnamed: 0,id,source,name,description,neighborhood_overview,host_id,host_name,host_since,host_location,host_about,host_about_len,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,latitude,longitude,property_type,room_type,accommodates,bathrooms,bathrooms_text,bedrooms,beds,amenities,price,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,number_of_reviews_l30d,availability_eoy,number_of_reviews_ly,estimated_occupancy_l365d,estimated_revenue_l365d,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
17,20,100186,city scrape,Large Modern Park Slope 1BR with Balcony,A modern apartment in a quiet but fun area.,NaN,526805,Mi,2011-04-21,United States,"A professor, based in the UK but working part ...",70,within a few hours,100%,62%,t,Gowanus,1.0,1.0,"['email', 'phone']",t,t,NaN,Gowanus,Brooklyn,40.66952,-73.99201,Entire condo,Entire home/apt,3,1.0,1 bath,1.0,2.0,"[""Baking sheet"", ""Oven"", ""Dedicated workspace""...",$100.00,30,90,30.0,30.0,90.0,90.0,30.0,90.0,NaN,t,0,0,0,89,2025-03-03,124,5,0,89,5,255,25500.0,2011-06-05,2024-12-01,4.94,4.97,4.91,4.96,4.95,4.81,4.89,NaN,f,1,1,0,0,0.74