# 서울시 부동산 2024 (2024.csv)

## 문제 0 - 데이터 로딩
데이터는 다음 경로에서 읽어옵니다: `2024.csv`  
encoding="cp949" 옵션 권장

In [1]:
import pandas as pd

df = pd.read_csv('2024.csv', encoding= 'cp949')
print(df.shape)

df.head()

(77523, 21)

C:\Users\까치\AppData\Local\Temp\ipykernel_90656\3528408005.py:3: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('2024.csv', encoding= 'cp949')

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
0,2024,11380,은평구,10200,녹번동,1.0,대지,86.0,125.0,성원빌라(86-125),...,16400,53.07,25.0000,4.0,NaN,NaN,1991.0,연립다세대,중개거래,서울 은평구
1,2024,11500,강서구,10300,화곡동,1.0,대지,924.0,4.0,팔팔빌라,...,35000,39.24,27.0000,2.0,NaN,NaN,1986.0,연립다세대,직거래,NaN
2,2024,11560,영등포구,11100,당산동1가,1.0,대지,143.0,0.0,다솔시티하임,...,30000,29.54,14.0000,5.0,NaN,NaN,2017.0,연립다세대,직거래,NaN
3,2024,11560,영등포구,12800,양평동4가,1.0,대지,220.0,0.0,해울빌,...,36000,40.41,63.6400,3.0,NaN,NaN,2021.0,오피스텔,중개거래,서울 용산구
4,2024,11410,서대문구,11200,대현동,1.0,대지,90.0,77.0,유씨유 이대,...,19300,17.31,30.8725,5.0,NaN,NaN,2018.0,오피스텔,중개거래,서울 서대문구

### 문제 1 — 조건 필터링(AND)
- 자치구명이 '강남구' **이면서** 건물용도가 '오피스텔'인 행만 필터링하세요.

In [2]:
df1 = df

cond_local = (df1['자치구명'] == '강남구')
cond_Build_use = (df1['건물용도'] == '오피스텔')

all_cond = cond_local & cond_Build_use

df1 = df1[all_cond]

df1.head()

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
39,2024,11680,강남구,10500,삼성동,1.0,대지,141.0,10.0,삼성동 롯데캐슬 클라쎄,...,51000,29.373,43.2521,5.0,NaN,NaN,2019.0,오피스텔,중개거래,서울 강남구
80,2024,11680,강남구,10100,역삼동,1.0,대지,823.0,33.0,강남루덴스 오피스텔,...,39000,27.640,43.9800,5.0,NaN,NaN,2021.0,오피스텔,직거래,NaN
289,2024,11680,강남구,11200,자곡동,1.0,대지,655.0,0.0,강남 푸르지오시티 2차(PRUGIO CITYⅡ),...,15000,21.872,28.9680,4.0,NaN,NaN,2014.0,오피스텔,중개거래,서울 강남구
324,2024,11680,강남구,10100,역삼동,1.0,대지,719.0,24.0,역삼역센트럴푸르지오시티,...,57000,39.304,62.7200,7.0,NaN,NaN,2019.0,오피스텔,중개거래,서울 강남구
326,2024,11680,강남구,10100,역삼동,1.0,대지,822.0,7.0,목화밀라트,...,31500,31.330,48.1300,16.0,NaN,NaN,2004.0,오피스텔,중개거래,서울 강남구

### 문제 2 — 조건 필터링(OR)
- 층(`층`)이 10층 이상 **또는** 물건금액(만원)이 100000 이상인 행만 필터링하세요.

In [3]:
df2 = df

cond_floar = (df['층'] <= 10)
cond_price = (df['물건금액(만원)']) <= 100000

all_cond2 = cond_floar | cond_price

df2 = df2[all_cond2]

df2.head()

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
0,2024,11380,은평구,10200,녹번동,1.0,대지,86.0,125.0,성원빌라(86-125),...,16400,53.07,25.0000,4.0,NaN,NaN,1991.0,연립다세대,중개거래,서울 은평구
1,2024,11500,강서구,10300,화곡동,1.0,대지,924.0,4.0,팔팔빌라,...,35000,39.24,27.0000,2.0,NaN,NaN,1986.0,연립다세대,직거래,NaN
2,2024,11560,영등포구,11100,당산동1가,1.0,대지,143.0,0.0,다솔시티하임,...,30000,29.54,14.0000,5.0,NaN,NaN,2017.0,연립다세대,직거래,NaN
3,2024,11560,영등포구,12800,양평동4가,1.0,대지,220.0,0.0,해울빌,...,36000,40.41,63.6400,3.0,NaN,NaN,2021.0,오피스텔,중개거래,서울 용산구
4,2024,11410,서대문구,11200,대현동,1.0,대지,90.0,77.0,유씨유 이대,...,19300,17.31,30.8725,5.0,NaN,NaN,2018.0,오피스텔,중개거래,서울 서대문구

### 문제 3 — 결측치 조건
- 취소일이 결측(`NaN`)인 행만 필터링하세요. (거래 취소가 없는 건)

In [4]:
df3 = df

df3 = df3[df3['취소일'].isnull()]

print(f'취소일 결측치 개수 : {df3['취소일'].isnull().sum()}')
df3.head()

취소일 결측치 개수 : 74351

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
0,2024,11380,은평구,10200,녹번동,1.0,대지,86.0,125.0,성원빌라(86-125),...,16400,53.07,25.0000,4.0,NaN,NaN,1991.0,연립다세대,중개거래,서울 은평구
1,2024,11500,강서구,10300,화곡동,1.0,대지,924.0,4.0,팔팔빌라,...,35000,39.24,27.0000,2.0,NaN,NaN,1986.0,연립다세대,직거래,NaN
2,2024,11560,영등포구,11100,당산동1가,1.0,대지,143.0,0.0,다솔시티하임,...,30000,29.54,14.0000,5.0,NaN,NaN,2017.0,연립다세대,직거래,NaN
3,2024,11560,영등포구,12800,양평동4가,1.0,대지,220.0,0.0,해울빌,...,36000,40.41,63.6400,3.0,NaN,NaN,2021.0,오피스텔,중개거래,서울 용산구
4,2024,11410,서대문구,11200,대현동,1.0,대지,90.0,77.0,유씨유 이대,...,19300,17.31,30.8725,5.0,NaN,NaN,2018.0,오피스텔,중개거래,서울 서대문구

### 문제 4 — 특정 값 필터링
- 신고구분이 '직거래'인 행만 필터링하세요.

In [5]:
df4 = df

cond_report = df4['신고구분'] == '직거래'

df4 = df4[cond_report]

df4.head()

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
1,2024,11500,강서구,10300,화곡동,1.0,대지,924.0,4.0,팔팔빌라,...,35000,39.24,27.0,2.0,NaN,NaN,1986.0,연립다세대,직거래,NaN
2,2024,11560,영등포구,11100,당산동1가,1.0,대지,143.0,0.0,다솔시티하임,...,30000,29.54,14.0,5.0,NaN,NaN,2017.0,연립다세대,직거래,NaN
5,2024,11590,동작구,10900,신대방동,NaN,NaN,NaN,NaN,NaN,...,744000,1502.31,534.0,NaN,NaN,NaN,1987.0,단독다가구,직거래,NaN
8,2024,11230,동대문구,10600,장안동,1.0,대지,580.0,0.0,장안위더스빌,...,76000,107.97,0.0,16.0,NaN,NaN,2011.0,아파트,직거래,NaN
41,2024,11530,구로구,11000,온수동,1.0,대지,23.0,0.0,아델리안,...,24600,35.40,21.0,2.0,NaN,NaN,2019.0,연립다세대,직거래,NaN

### 문제 5 — 정렬
- 물건금액(만원) 기준 **내림차순** 정렬 후 상위 10행을 출력하세요.

In [6]:
df5 = df

df5 = df5.sort_values(by='물건금액(만원)', ascending= False)

df5.head()

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
57768,2024,11680,강남구,10700,신사동,NaN,NaN,NaN,NaN,NaN,...,2850000,305.620,326.0,NaN,NaN,NaN,1982.0,단독다가구,중개거래,서울 서초구
20409,2024,11170,용산구,13100,한남동,1.0,대지,829.0,0.0,나인원한남,...,2200000,273.412,0.0,1.0,NaN,NaN,2019.0,아파트,직거래,NaN
39252,2024,11170,용산구,13100,한남동,1.0,대지,829.0,0.0,나인원한남,...,2000000,273.942,0.0,1.0,NaN,NaN,2019.0,아파트,중개거래,서울 용산구
54876,2024,11680,강남구,10700,신사동,NaN,NaN,NaN,NaN,NaN,...,1800000,599.650,226.0,NaN,NaN,20240726.0,1988.0,단독다가구,중개거래,서울 강남구
54856,2024,11680,강남구,10700,신사동,NaN,NaN,NaN,NaN,NaN,...,1800000,599.650,226.3,NaN,NaN,NaN,1988.0,단독다가구,중개거래,서울 강남구

### 문제 6 — 다중 정렬
- 건축년도 **오름차순**, 건물면적(㎡) **내림차순**으로 다중 정렬하세요.

In [7]:
df6 = df

df6 = df5.sort_values(by=['건축년도','건물면적(㎡)'], ascending= [True,False])

df5.head()

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,물건금액(만원),건물면적(㎡),토지면적(㎡),층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
57768,2024,11680,강남구,10700,신사동,NaN,NaN,NaN,NaN,NaN,...,2850000,305.620,326.0,NaN,NaN,NaN,1982.0,단독다가구,중개거래,서울 서초구
20409,2024,11170,용산구,13100,한남동,1.0,대지,829.0,0.0,나인원한남,...,2200000,273.412,0.0,1.0,NaN,NaN,2019.0,아파트,직거래,NaN
39252,2024,11170,용산구,13100,한남동,1.0,대지,829.0,0.0,나인원한남,...,2000000,273.942,0.0,1.0,NaN,NaN,2019.0,아파트,중개거래,서울 용산구
54876,2024,11680,강남구,10700,신사동,NaN,NaN,NaN,NaN,NaN,...,1800000,599.650,226.0,NaN,NaN,20240726.0,1988.0,단독다가구,중개거래,서울 강남구
54856,2024,11680,강남구,10700,신사동,NaN,NaN,NaN,NaN,NaN,...,1800000,599.650,226.3,NaN,NaN,NaN,1988.0,단독다가구,중개거래,서울 강남구

### 문제 7 — 열 제거
- 분석에 불필요하다고 가정하고 `권리구분` 열을 제거한 새로운 DataFrame을 만들고 컬럼 목록을 출력하세요.

In [8]:
df7 = df
print(f'제거 전 shape : {df7.shape}')

df7 = df7.drop(columns='권리구분')

print(f'제거 후 shape : {df7.shape}')
df7.head()

제거 전 shape : (77523, 21)
제거 후 shape : (77523, 20)

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,계약일,물건금액(만원),건물면적(㎡),토지면적(㎡),층,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
0,2024,11380,은평구,10200,녹번동,1.0,대지,86.0,125.0,성원빌라(86-125),20241014,16400,53.07,25.0000,4.0,NaN,1991.0,연립다세대,중개거래,서울 은평구
1,2024,11500,강서구,10300,화곡동,1.0,대지,924.0,4.0,팔팔빌라,20241014,35000,39.24,27.0000,2.0,NaN,1986.0,연립다세대,직거래,NaN
2,2024,11560,영등포구,11100,당산동1가,1.0,대지,143.0,0.0,다솔시티하임,20241014,30000,29.54,14.0000,5.0,NaN,2017.0,연립다세대,직거래,NaN
3,2024,11560,영등포구,12800,양평동4가,1.0,대지,220.0,0.0,해울빌,20241014,36000,40.41,63.6400,3.0,NaN,2021.0,오피스텔,중개거래,서울 용산구
4,2024,11410,서대문구,11200,대현동,1.0,대지,90.0,77.0,유씨유 이대,20241014,19300,17.31,30.8725,5.0,NaN,2018.0,오피스텔,중개거래,서울 서대문구

### 문제 8 — 열 이름 변경
- `물건금액(만원)`→`거래금액_만원`, `건물면적(㎡)`→`건물면적_m2`, `토지면적(㎡)`→`토지면적_m2`로 변경하세요.

In [9]:
df8 = df

df8 = df8.rename(columns={ 
     '물건금액(만원)' : '거래금액_만원' 
    ,'건물면적(㎡)'   : '건물면적_m2'
    ,'토지면적(㎡)'   : '토지면적_m2'
})

df8

,접수연도,자치구코드,자치구명,법정동코드,법정동명,지번구분,지번구분명,본번,부번,건물명,...,거래금액_만원,건물면적_m2,토지면적_m2,층,권리구분,취소일,건축년도,건물용도,신고구분,신고한 개업공인중개사 시군구명
0,2024,11380,은평구,10200,녹번동,1.0,대지,86.0,125.0,성원빌라(86-125),...,16400,53.07,25.0000,4.0,NaN,NaN,1991.0,연립다세대,중개거래,서울 은평구
1,2024,11500,강서구,10300,화곡동,1.0,대지,924.0,4.0,팔팔빌라,...,35000,39.24,27.0000,2.0,NaN,NaN,1986.0,연립다세대,직거래,NaN
2,2024,11560,영등포구,11100,당산동1가,1.0,대지,143.0,0.0,다솔시티하임,...,30000,29.54,14.0000,5.0,NaN,NaN,2017.0,연립다세대,직거래,NaN
3,2024,11560,영등포구,12800,양평동4가,1.0,대지,220.0,0.0,해울빌,...,36000,40.41,63.6400,3.0,NaN,NaN,2021.0,오피스텔,중개거래,서울 용산구
4,2024,11410,서대문구,11200,대현동,1.0,대지,90.0,77.0,유씨유 이대,...,19300,17.31,30.8725,5.0,NaN,NaN,2018.0,오피스텔,중개거래,서울 서대문구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77518,2024,11530,구로구,10700,개봉동,1.0,대지,0170,0033,금석연립(170-33),...,9190,53.61,124.0000,1.0,NaN,20240207.0,1981.0,연립다세대,중개거래,서울 강남구
77519,2024,11530,구로구,10700,개봉동,1.0,대지,0170,0033,금석연립(170-33),...,9190,53.61,124.0000,1.0,NaN,20240207.0,1981.0,연립다세대,중개거래,서울 강남구
77520,2024,11530,구로구,10700,개봉동,1.0,대지,0170,0033,금석연립(170-33),...,9740,53.61,124.0000,2.0,NaN,20240207.0,1981.0,연립다세대,중개거래,서울 강남구
77521,2024,11440,마포구,11000,노고산동,NaN,NaN,NaN,NaN,NaN,...,195000,157.45,116.7000,NaN,NaN,20240417.0,1988.0,단독다가구,NaN,NaN
77522,2024,11305,강북구,10100,미아동,NaN,NaN,NaN,NaN,NaN,...,164000,293.08,136.0000,NaN,NaN,20240905.0,1994.0,단독다가구,NaN,NaN

### 문제 9 — 결측치 개수
- 각 열의 결측치 개수를 한 번에 확인하세요.

In [10]:
df9 = df

df9_null = df9.isnull().sum()

df9_null

접수연도                    0
자치구코드                   0
자치구명                    1
법정동코드                   0
법정동명                    0
지번구분                 2558
지번구분명                2558
본번                   2559
부번                   2559
건물명                  2559
계약일                     0
물건금액(만원)                0
건물면적(㎡)                 0
토지면적(㎡)              5077
층                    2558
권리구분                76823
취소일                 74351
건축년도                  267
건물용도                    0
신고구분                    2
신고한 개업공인중개사 시군구명     8854
dtype: int64

### 문제 10 — 결측치 채우기(수치형)
- 건축년도 결측치를 건축년도 **중앙값**으로 채운 새 DataFrame을 만들고, 채운 후 해당 열의 결측치 개수를 출력하세요.

In [11]:
df10 = df
build_year = df10['건축년도']
print(f'결측치 대체 전 : {build_year.isnull().sum()}')

median_year = build_year.median()
print(f'대체 연도 : {median_year}')

build_year = build_year.fillna(median_year)
df10['건축년도'] = build_year

print(f'결측치 대체 후 : {build_year.isnull().sum()}')

결측치 대체 전 : 267
대체 연도 : 2004.0
결측치 대체 후 : 0

### 문제 11 — 결측치 채우기(문자열)
- 건물명 결측치를 '미기재'로 채우고, 채운 후 해당 열의 결측치 개수를 출력하세요.

In [ ]:
df11 = df
build_name = df11['건물명']
print(f'결측치 대체 전 : {build_name.isnull().sum()}')

build_name = build_name.fillna('미기재')
print(f'결측치 대체 후 : {build_name.isnull().sum()}')

결측치 대체 전 : 2559
결측치 대체 후 : 0

### 문제 12 — 중복 확인 및 제거(subset)
- 중복 기준을 `['자치구명','법정동명','계약일','건물면적(㎡)','물건금액(만원)']`으로 하여 중복 개수를 확인하고, 이를 기준으로 중복을 제거한 뒤 제거 전/후 행 수를 비교하세요.

In [ ]:
df12 = df
print(f'중복치 제거 전 : {df12.duplicated().sum()}')

columns = ['자치구명','법정동명','계약일','건물면적(㎡)','물건금액(만원)']

df12 = df12.drop_duplicates(subset=columns, keep=False)

print(f'중복치 제거 후 : {df12.duplicated().sum()}')

중복치 제거 전 : 1427
중복치 제거 후 : 0